### ISSUE TITLE
Custom level for blocks with special nbt

### ISSUE THREAD

**Issue by WhiteMat** [BentoBoxWorld/Level#207]
### Description :

**Is your feature request related to a problem?**

No, this is just a feature request.

**Describe the solution you'd like us to implement.**

Is it possible to add nbt reading to island level calculation?
Config example, with no incrementation:
`block-nbt:`
`  SPAWNER:`
`    level: 50`
`    nbt:`
`     '{SpawnCount:0,SpawnRange:0,Delay:0,MinSpawnDelay:0,MaxSpawnDelay:0,MaxNearbyEntities:0,RequiredPlayerRange:0,SpawnData:{id:""minecraft:armor_stand"",ArmorItems:[{},{},{},{id:""minecraft:red_stained_glass"",Count:1b,tag:5}]}}'`

**Describe alternatives you've considered.**
### Additional context

Thanks for reading.

**Comment by tastybento** [comment]
Just to clarify, what does the `level` indicate? Is that the value of the SPAWNER that has that NBT?

**Comment by WhiteMat** [comment]
Sorry, level is value of block.
same as :
```
# This section lists the value of a block. Value must be an integer.
# Any blocks not listed will have a value of 0. AIR is always zero.
# Format is MATERIAL: value 

blocks:
  ACACIA_BUTTON: 1 <- here
  ACACIA_DOOR: 1 <- here
  ACACIA_FENCE: 1 <- here
  ACACIA_FENCE_GATE: 1 <- here
  ACACIA_LEAVES: 0 <- here
  ACACIA_LOG: 0 <- here
```
```
blocks-nbt:
  SPAWNER:
    value: 50
    nbt: {SpawnCount:0,SpawnRange:0,Delay:0,MinSpawnDelay:0,MaxSpawnDelay:0,MaxNearbyEntities:0,RequiredPlayerRange:0,SpawnData:{id:""minecraft:armor_stand"",ArmorItems:[{},{},{},{id:""minecraft:red_stained_glass"",Count:1b,tag:5}]}}'
```
